matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      language: node_js
      node_js: "14"

    - os: windows
      language: node_js
      node_js: "14"

    - os: linux
      language: node_js
      node_js: "14"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  npm install
  npm run build

branches:
  only:
    - master